[package]
name = "analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
widestring = "1.0.2"
unicode-segmentation = "1.9.0"
regex = "1.7.0"
iter_tools = "0.1.4"